spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:postgresql://product-db:5432/inventorytdb
    username: postgres
    password: postgres
  #    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8082
